{{- if eq .Values.rollouts.brotcast.type "canary" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: brotcast
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brotcast
  template:
    metadata:
      labels:
        app: brotcast
    spec:
      containers:
      - name: brotcast
        image: {{ .Values.brotcast_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        env:
        - name: BROADCAST_DRIVER
          value: reverb
        - name: BREZEL_BROTCAST_SERVER_PORT
          value: "8086"
        - name: BREZEL_BROTCAST_APP_ID
          value: brezel
        - name: BREZEL_BROTCAST_KEY
          value: brotcast
        - name: BREZEL_BROTCAST_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "brezel.runtimeSecretName" . }}
              key: BREZEL_BROTCAST_SECRET
        resources:
          limits:
            cpu: {{ .Values.brotcast_resources.limits.cpu }}
            memory: {{ .Values.brotcast_resources.limits.memory }}
          requests:
            cpu: {{ .Values.brotcast_resources.requests.cpu }}
            memory: {{ .Values.brotcast_resources.requests.memory }}
      imagePullSecrets:
      - name: {{ include "brezel.imagePullSecretName" . }}
{{- if eq .Values.rollouts.brotcast.type "canary" }}
  strategy:
    canary:
      stableService: brotcast
      canaryService: brotcast-canary
      trafficRouting:
        nginx:
          stableIngress: brotcast
      steps:
      - setWeight: 20
      - pause:
          duration: {{ .Values.rollouts.brotcast.pause_duration_seconds }}
      - setWeight: 40
      - pause:
          duration: {{ .Values.rollouts.brotcast.pause_duration_seconds }}
      - setWeight: 60
      - pause:
          duration: {{ .Values.rollouts.brotcast.pause_duration_seconds }}
      - setWeight: 80
      - pause:
          duration: {{ .Values.rollouts.brotcast.pause_duration_seconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: brotcast-canary
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: brotcast
  ports:
  - name: brotcast
    port: 8086
    targetPort: 8086
{{- end }}
