{{- if eq .Values.rollouts.phpmyadmin.type "canary" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: phpmyadmin
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: Always
        env:
        - name: PMA_HOST
          value: "{{ if .Values.with_database_pod }}{{ include "brezel.mysqlServiceName" . }}{{ else }}{{ .Values.db_host }}{{ end }}"
        - name: PMA_PORT
          value: "{{ if .Values.with_database_pod }}3306{{ else }}{{ .Values.db_port }}{{ end }}"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "brezel.runtimeSecretName" . }}
              key: MYSQL_PASSWORD
        - name: UPLOAD_LIMIT
          value: "2048M"
        - name: MAX_EXECUTION_TIME
          value: "600"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.phpmyadmin_resources.limits.cpu }}
            memory: {{ .Values.phpmyadmin_resources.limits.memory }}
          requests:
            cpu: {{ .Values.phpmyadmin_resources.requests.cpu }}
            memory: {{ .Values.phpmyadmin_resources.requests.memory }}
{{- if eq .Values.rollouts.phpmyadmin.type "canary" }}
  strategy:
    canary:
      stableService: phpmyadmin
      canaryService: phpmyadmin-canary
      trafficRouting:
        nginx:
          stableIngress: phpmyadmin
      steps:
      - setWeight: 20
      - pause:
          duration: {{ .Values.rollouts.phpmyadmin.pause_duration_seconds }}
      - setWeight: 40
      - pause:
          duration: {{ .Values.rollouts.phpmyadmin.pause_duration_seconds }}
      - setWeight: 60
      - pause:
          duration: {{ .Values.rollouts.phpmyadmin.pause_duration_seconds }}
      - setWeight: 80
      - pause:
          duration: {{ .Values.rollouts.phpmyadmin.pause_duration_seconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-canary
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
{{- end }}
