apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global_gitlab_registry_data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: brezel-api
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_KEY: "base64:{{ .Values.app_key }}"
  TENANCY_PASSWORD: "{{ if .Values.with_database_pod }}{{ .Values.mysql_password }}{{ else }}{{ .Values.db_password }}{{ end }}"
  MYSQL_PASSWORD: "{{ if .Values.with_database_pod }}{{ .Values.mysql_password }}{{ else }}{{ .Values.db_password }}{{ end }}"
  BREZEL_BROTCAST_SECRET: "{{ .Values.brotcast_secret }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.s3_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3_secret_key }}"
  S3_ACCESS_KEY_ID: "{{ .Values.s3_access_key }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.s3_secret_key }}"
  {{- range $key, $value := .Values.secret_env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $system, $envs := .Values.system_secret_envs }}
  {{- range $key, $value := $envs }}
  BREZEL_SYSTEM_{{ $system }}_{{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
---
{{- if .Values.with_database_pod }}
apiVersion: v1
kind: Secret
metadata:
  name: brezel-mysql
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql_password }}"
{{- end }}
