{{- if eq .Values.rollouts.spa.type "canary" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: brezel-spa
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brezel-spa
  template:
    metadata:
      labels:
        app: brezel-spa
        configVersion: {{ include "brezel.spaConfigVersion" . }}
    spec:
      containers:
      - name: brezel-spa
        image: {{ .Values.spa_image }}
        imagePullPolicy: Always
        workingDir: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.spa_resources.limits.cpu }}
            memory: {{ .Values.spa_resources.limits.memory }}
          requests:
            cpu: {{ .Values.spa_resources.requests.cpu }}
            memory: {{ .Values.spa_resources.requests.memory }}
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
          readOnly: true
      imagePullSecrets:
      - name: {{ include "brezel.imagePullSecretName" . }}
      volumes:
      - name: config-volume
        configMap:
          name: brezel-spa
{{- if eq .Values.rollouts.spa.type "canary" }}
  strategy:
    canary:
      stableService: brezel-spa
      canaryService: brezel-spa-canary
      trafficRouting:
        nginx:
          stableIngress: brezel-spa
      steps:
      - setWeight: 20
      - pause:
          duration: {{ .Values.rollouts.spa.pause_duration_seconds }}
      - setWeight: 40
      - pause:
          duration: {{ .Values.rollouts.spa.pause_duration_seconds }}
      - setWeight: 60
      - pause:
          duration: {{ .Values.rollouts.spa.pause_duration_seconds }}
      - setWeight: 80
      - pause:
          duration: {{ .Values.rollouts.spa.pause_duration_seconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: brezel-spa-canary
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: brezel-spa
  ports:
  - port: 80
    targetPort: 80
{{- end }}
